In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!ln -s /content/drive/MyDrive/ /gdrive

In [3]:
!cp -r /gdrive/aicon/aicon_retrailer/npy data/
!cp /gdrive/aicon/aicon_retrailer/sample_submission.csv data/
!cp -r /gdrive/Team_DimensionSTP/NL/신민정 data/

In [5]:
import numpy as np
import pandas as pd

In [7]:
pred1 = np.load("./data/pred_roberta_base_whole_0.npy")
pred2 = np.load("./data/신민정/roberta_small/pred_klue_roberta_small_1.npy")
pred3 = np.load("./data/신민정/xml_roberta_base/pred_xml_1.npy")

In [8]:
pred1

array([[ 9.6324329e+00,  8.9810791e+00,  5.3185339e+00, ...,
         1.8130133e+00,  2.8840806e+00, -2.4185507e-01],
       [ 1.0001112e+01,  8.1201115e+00,  4.8124371e+00, ...,
         2.1260829e+00,  3.4797580e+00, -3.8149324e-01],
       [ 1.0073571e+01,  7.9485030e+00,  4.7659740e+00, ...,
         2.2230208e+00,  3.6699405e+00, -2.5046405e-01],
       ...,
       [-1.3290398e+00,  4.5141548e-01,  5.6426339e-02, ...,
         4.6781251e-01,  5.5249138e+00,  1.0868691e+01],
       [-1.1660599e+00,  7.6584250e-01,  2.5209346e-01, ...,
         2.2013918e-01,  5.4119077e+00,  1.0674691e+01],
       [-1.6156952e+00, -4.4615320e-03, -9.1096413e-01, ...,
         1.1560389e+00,  4.5492668e+00,  1.0143112e+01]], dtype=float32)

In [9]:
pred2

array([[ 8.912011  ,  9.536626  ,  5.0793962 , ...,  1.0547609 ,
         3.2877588 ,  0.9935492 ],
       [ 9.526313  ,  8.431031  ,  5.2951007 , ...,  2.0112803 ,
         4.0878277 ,  1.0971729 ],
       [ 9.425535  ,  7.709252  ,  5.0993824 , ...,  2.23672   ,
         4.14279   ,  0.72773594],
       ...,
       [-0.5227586 ,  0.58644795, -0.80853015, ...,  0.7493969 ,
         5.414763  , 11.310577  ],
       [-0.7128612 ,  0.5264113 , -0.5311182 , ...,  0.301177  ,
         5.2655478 , 11.010524  ],
       [-0.2489403 ,  1.1432892 , -1.2908722 , ...,  1.1849071 ,
         4.1568513 ,  9.929515  ]], dtype=float32)

In [10]:
pred3

array([[ 8.603331  ,  8.960693  ,  5.99396   , ...,  0.35223866,
         2.3119378 ,  0.38300413],
       [ 9.442897  ,  7.950493  ,  5.4286656 , ...,  1.1392838 ,
         3.34654   ,  0.5699694 ],
       [ 9.39408   ,  8.302434  ,  4.8529797 , ...,  1.0592331 ,
         3.274502  ,  0.7044664 ],
       ...,
       [-0.17496172, -0.24187775,  0.87215346, ...,  0.77292854,
         5.3691664 , 10.471138  ],
       [-0.48438066,  0.01339704,  0.3310213 , ...,  0.8099052 ,
         4.7248955 , 10.777735  ],
       [ 1.4341596 ,  1.554359  ,  0.22593993, ...,  1.7087984 ,
         3.3252861 ,  7.0077977 ]], dtype=float32)

In [11]:
pred1.shape

(40730, 118)

In [12]:
pred2.shape

(40730, 118)

In [13]:
pred3.shape

(40730, 118)

In [14]:
x = pred1 * 0.4 + pred2 * 0.3 + pred3 * 0.3

In [15]:
x

array([[ 9.107576  ,  9.141628  ,  5.4494205 , ...,  1.1473053 ,
         2.8335414 ,  0.31622398],
       [ 9.691208  ,  8.162502  ,  5.1421046 , ...,  1.7956026 ,
         3.6222138 ,  0.3475454 ],
       [ 9.675313  ,  7.9829073 ,  4.8920984 , ...,  1.8779943 ,
         3.6931636 ,  0.3294751 ],
       ...,
       [-0.740932  ,  0.28393725,  0.04165754, ...,  0.64382267,
         5.4451447 , 10.881991  ],
       [-0.8255966 ,  0.4682795 ,  0.04080832, ...,  0.42138034,
         5.161896  , 10.8063545 ],
       [-0.2907123 ,  0.80750984, -0.68386537, ...,  1.3305272 ,
         4.064348  ,  9.138439  ]], dtype=float32)

In [16]:
x.shape

(40730, 118)

In [17]:
submission = pd.read_csv('./data/sample_submission.csv')

In [18]:
submission.head()

conv_num    intent
0      9710  카테고리_채우기
1      9711  카테고리_채우기
2      9728  카테고리_채우기
3      9737  카테고리_채우기
4     11050  카테고리_채우기

In [19]:
pred = np.argmax(x,1)
submission['label'] = pred

In [20]:
map_dict = {'AS_날짜_요청': 0,'AS_날짜_질문': 1,'AS_방법_요청': 2,'AS_방법_질문': 3,'AS_비용_요청': 4,'AS_비용_질문': 5,
                        'AS_시간_질문': 6,'AS_일반_질문': 7,'결제_방식_질문': 8,'결제_수단_질문': 9,'결제_시기_질문': 10,'결제_영수증_질문': 11,
                        '결제_오류_질문': 12,'결제_일반_질문': 13,'결제_일반_확인': 14,'결제_재결제_질문': 15,'결제_추가_질문': 16,
                        '결제_취소_질문': 17,'결제_할인_질문': 18,'교환|반품|환불_방법_요청': 19,'교환|반품|환불_방법_질문': 20,
                        '교환|반품|환불_방법_확인': 21,'교환|반품|환불_비용_질문': 22,'교환|반품|환불_시간_요청': 23,
                        '교환|반품|환불_시간_질문': 24,'교환|반품|환불_일반_요청': 25,'교환|반품|환불_일반_질문': 26,
                        '교환|반품|환불_일반_확인': 27,'구매_예약_요청': 28,'구매_예약_질문': 29,'구매_제품_요청': 30,'구매_제품_질문': 31,
                        '매장_이용_요청': 32,'매장_이용_질문': 33,'매장_정보_질문': 34,'멤버십_사용_질문': 35,'멤버십_적립_질문': 36,
                        '배송_날짜_요청': 37,'배송_날짜_질문': 38,'배송_날짜_확인': 39,'배송_방법_요청': 40,'배송_방법_질문': 41,
                        '배송_방법_확인': 42,'배송_비용_질문': 43,'배송_오류_질문': 44,'배송_오류_확인': 45,'배송_일반_요청': 46,
                        '배송_일반_질문': 47,'배송_일반_확인': 48,'배송_지역_요청': 49,'배송_지역_질문': 50,'배송_택배사_질문': 51,
                        '부가서비스_날짜_요청': 52,'부가서비스_날짜_질문': 53,'부가서비스_방법_요청': 54,'부가서비스_방법_질문': 55,
                        '부가서비스_비용_요청': 56,'부가서비스_비용_질문': 57,'웹사이트_사용_질문': 58,'웹사이트_오류_질문': 59,
                        '제품_가격_비교': 60,'제품_가격_요청': 61,'제품_가격_질문': 62,'제품_가격_확인': 63,'제품_구성_요청': 64,
                        '제품_구성_질문': 65,'제품_구성_확인': 66,'제품_날짜_질문': 67,'제품_방법_요청': 68,'제품_방법_질문': 69,
                        '제품_방법_확인': 70,'제품_불량_요청': 71,'제품_불량_질문': 72,'제품_불량_확인': 73,'제품_소재_질문': 74,
                        '제품_시용_요청': 75,'제품_시용_질문': 76,'제품_용도_질문': 77,'제품_용도_확인': 78,'제품_원산지_질문': 79,
                        '제품_일반_비교': 80,'제품_일반_요청': 81,'제품_일반_질문': 82,'제품_일반_확인': 83,'제품_입고_요청': 84,
                        '제품_입고_질문': 85,'제품_재고_요청': 86,'제품_재고_질문': 87,'제품_재고_확인': 88,'제품_정보_비교': 89,
                        '제품_정보_요청': 90,'제품_정보_질문': 91,'제품_정보_확인': 92,'제품_추천_비교': 93,'제품_추천_요청': 94,
                        '제품_추천_질문': 95,'제품_추천_확인': 96,'제품_커스텀_요청': 97,'제품_커스텀_질문': 98,'제품_품질_비교': 99,
                        '제품_품질_요청': 100,'제품_품질_질문': 101,'제품_품질_확인': 102,'제품_호환_질문': 103,'제품_호환_확인': 104,
                        '포장_방식_요청': 105,'포장_방식_질문': 106,'포장_비용_질문': 107,'포장_일반_질문': 108,'행사_기간_질문': 109,
                        '행사_기간_확인': 110,'행사_날짜_질문': 111,'행사_유형_질문': 112,'행사_유형_확인': 113,'행사_일반_질문': 114,
                        '행사_일반_확인': 115,'행사_정보_요청': 116,'행사_정보_질문': 117}

In [21]:
dict_map = {v : k for k, v in map_dict.items()}

dict_map

{0: 'AS_날짜_요청',
 1: 'AS_날짜_질문',
 2: 'AS_방법_요청',
 3: 'AS_방법_질문',
 4: 'AS_비용_요청',
 5: 'AS_비용_질문',
 6: 'AS_시간_질문',
 7: 'AS_일반_질문',
 8: '결제_방식_질문',
 9: '결제_수단_질문',
 10: '결제_시기_질문',
 11: '결제_영수증_질문',
 12: '결제_오류_질문',
 13: '결제_일반_질문',
 14: '결제_일반_확인',
 15: '결제_재결제_질문',
 16: '결제_추가_질문',
 17: '결제_취소_질문',
 18: '결제_할인_질문',
 19: '교환|반품|환불_방법_요청',
 20: '교환|반품|환불_방법_질문',
 21: '교환|반품|환불_방법_확인',
 22: '교환|반품|환불_비용_질문',
 23: '교환|반품|환불_시간_요청',
 24: '교환|반품|환불_시간_질문',
 25: '교환|반품|환불_일반_요청',
 26: '교환|반품|환불_일반_질문',
 27: '교환|반품|환불_일반_확인',
 28: '구매_예약_요청',
 29: '구매_예약_질문',
 30: '구매_제품_요청',
 31: '구매_제품_질문',
 32: '매장_이용_요청',
 33: '매장_이용_질문',
 34: '매장_정보_질문',
 35: '멤버십_사용_질문',
 36: '멤버십_적립_질문',
 37: '배송_날짜_요청',
 38: '배송_날짜_질문',
 39: '배송_날짜_확인',
 40: '배송_방법_요청',
 41: '배송_방법_질문',
 42: '배송_방법_확인',
 43: '배송_비용_질문',
 44: '배송_오류_질문',
 45: '배송_오류_확인',
 46: '배송_일반_요청',
 47: '배송_일반_질문',
 48: '배송_일반_확인',
 49: '배송_지역_요청',
 50: '배송_지역_질문',
 51: '배송_택배사_질문',
 52: '부가서비스_날짜_요청',
 53: '부가서비스_날짜_질문',
 54: '부가서비스_방법_요청',
 55: '부

In [22]:
def set_values(row, value):
    return value[row]

In [23]:
submission['intent'] = submission['label'].apply(set_values, args =(dict_map, ))
submission =submission.drop('label', axis=1)
submission.head()

conv_num    intent
0      9710  AS_날짜_질문
1      9711  AS_날짜_요청
2      9728  AS_날짜_요청
3      9737  AS_날짜_요청
4     11050  AS_날짜_요청

In [24]:
submission.to_csv("/gdrive/aicon/aicon_retrailer/result/softvoting_roberta_0.csv",index=False)